# python test.py ../configs/pointpillars/resample/nus/random/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.5.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method random --sample_rate 0.5 --model_name pointpillars --feature_model none --dataset nus
# python test.py ../configs/pointpillars/resample/nus/random/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.4.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method random --sample_rate 0.4 --model_name pointpillars --feature_model none --dataset nus
# python test.py ../configs/pointpillars/resample/nus/random/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.3.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method random --sample_rate 0.3 --model_name pointpillars --feature_model none --dataset nus
# python test.py ../configs/pointpillars/resample/nus/random/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.2.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method random --sample_rate 0.2 --model_name pointpillars --feature_model none --dataset nus
# python test.py ../configs/pointpillars/resample/nus/random/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.1.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method random --sample_rate 0.1 --model_name pointpillars --feature_model none --dataset nus

# python test.py ../configs/pointpillars/resample/nus/statistic/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.5.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method statistic --sample_rate 0.5 --model_name pointpillars --feature_model none --dataset nus
# python test.py ../configs/pointpillars/resample/nus/statistic/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.4.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method statistic --sample_rate 0.4 --model_name pointpillars --feature_model none --dataset nus
# python test.py ../configs/pointpillars/resample/nus/statistic/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.3.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method statistic --sample_rate 0.3 --model_name pointpillars --feature_model none --dataset nus
# python test.py ../configs/pointpillars/resample/nus/statistic/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.2.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method statistic --sample_rate 0.2 --model_name pointpillars --feature_model none --dataset nus
# python test.py ../configs/pointpillars/resample/nus/statistic/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.1.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method statistic --sample_rate 0.1 --model_name pointpillars --feature_model none --dataset nus

# python test.py ../configs/pointpillars/resample/nus/octree/10/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.5.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method octree10 --sample_rate 0.5 --model_name pointpillars --feature_model none --dataset nus
# python test.py ../configs/pointpillars/resample/nus/octree/10/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.4.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method octree10 --sample_rate 0.4 --model_name pointpillars --feature_model none --dataset nus
python test.py ../configs/pointpillars/resample/nus/octree/10/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.3.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method octree10 --sample_rate 0.3 --model_name pointpillars --feature_model none --dataset nus
python test.py ../configs/pointpillars/resample/nus/octree/10/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.2.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method octree10 --sample_rate 0.2 --model_name pointpillars --feature_model none --dataset nus
python test.py ../configs/pointpillars/resample/nus/octree/10/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.1.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method octree10 --sample_rate 0.1 --model_name pointpillars --feature_model none --dataset nus

# python test.py ../configs/pointpillars/resample/nus/grid_fps/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.5.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method grid_fps --sample_rate 0.5 --model_name pointpillars --feature_model none --dataset nus
# python test.py ../configs/pointpillars/resample/nus/grid_fps/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.4.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method grid_fps --sample_rate 0.4 --model_name pointpillars --feature_model none --dataset nus
# python test.py ../configs/pointpillars/resample/nus/grid_fps/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.3.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method grid_fps --sample_rate 0.3 --model_name pointpillars --feature_model none --dataset nus
# python test.py ../configs/pointpillars/resample/nus/grid_fps/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.2.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method grid_fps --sample_rate 0.2 --model_name pointpillars --feature_model none --dataset nus
# python test.py ../configs/pointpillars/resample/nus/grid_fps/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.1.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method grid_fps --sample_rate 0.1 --model_name pointpillars --feature_model none --dataset nus

# python test.py ../configs/pointpillars/resample/nus/grid_fps/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.08.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method grid_fps --sample_rate 0.08 --model_name pointpillars --feature_model none --dataset nus
# python test.py ../configs/pointpillars/resample/nus/grid_fps/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.06.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method grid_fps --sample_rate 0.06 --model_name pointpillars --feature_model none --dataset nus
# python test.py ../configs/pointpillars/resample/nus/grid_fps/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.04.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method grid_fps --sample_rate 0.04 --model_name pointpillars --feature_model none --dataset nus
# python test.py ../configs/pointpillars/resample/nus/grid_fps/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.02.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method grid_fps --sample_rate 0.02 --model_name pointpillars --feature_model none --dataset nus

# python test.py ../configs/pointpillars/resample/nus/fps/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.5.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method fps --sample_rate 0.5 --model_name pointpillars --feature_model none --dataset nus
# python test.py ../configs/pointpillars/resample/nus/fps/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.4.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method fps --sample_rate 0.4 --model_name pointpillars --feature_model none --dataset nus
# python test.py ../configs/pointpillars/resample/nus/fps/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.3.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method fps --sample_rate 0.3 --model_name pointpillars --feature_model none --dataset nus
# python test.py ../configs/pointpillars/resample/nus/fps/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.2.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method fps --sample_rate 0.2 --model_name pointpillars --feature_model none --dataset nus
# python test.py ../configs/pointpillars/resample/nus/fps/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.1.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method fps --sample_rate 0.1 --model_name pointpillars --feature_model none --dataset nus

python test.py ../configs/pointpillars/resample/nus/fps/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.08.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method fps --sample_rate 0.08 --model_name pointpillars --feature_model none --dataset nus
python test.py ../configs/pointpillars/resample/nus/fps/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.06.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method fps --sample_rate 0.06 --model_name pointpillars --feature_model none --dataset nus
python test.py ../configs/pointpillars/resample/nus/fps/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.04.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method fps --sample_rate 0.04 --model_name pointpillars --feature_model none --dataset nus

# python test.py ../configs/pointpillars/resample/nus/random/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.5.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method random --sample_rate 0.5 --model_name pointpillars --feature_model none --dataset nus
# python test.py ../configs/pointpillars/resample/nus/random/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.3.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method random --sample_rate 0.3 --model_name pointpillars --feature_model none --dataset nus
# python test.py ../configs/pointpillars/resample/nus/random/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.1.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method random --sample_rate 0.1 --model_name pointpillars --feature_model none --dataset nus
# python test.py ../configs/pointpillars/resample/nus/random/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.08.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method random --sample_rate 0.08 --model_name pointpillars --feature_model none --dataset nus
# python test.py ../configs/pointpillars/resample/nus/random/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.06.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method random --sample_rate 0.06 --model_name pointpillars --feature_model none --dataset nus


# python test.py ../configs/pointpillars/resample/nus/statistic/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.5.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method statistic --sample_rate 0.5 --model_name pointpillars --feature_model none --dataset nus
# python test.py ../configs/pointpillars/resample/nus/statistic/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.3.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method statistic --sample_rate 0.3 --model_name pointpillars --feature_model none --dataset nus
# python test.py ../configs/pointpillars/resample/nus/statistic/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.1.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method statistic --sample_rate 0.1 --model_name pointpillars --feature_model none --dataset nus

# python test.py ../configs/pointpillars/resample/nus/octree/6/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.5.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method octree6 --sample_rate 0.5 --model_name pointpillars --feature_model none --dataset nus
# python test.py ../configs/pointpillars/resample/nus/octree/6/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.3.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method octree6 --sample_rate 0.3 --model_name pointpillars --feature_model none --dataset nus
# python test.py ../configs/pointpillars/resample/nus/octree/6/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.1.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method octree6 --sample_rate 0.1 --model_name pointpillars --feature_model none --dataset nus
# python test.py ../configs/pointpillars/resample/nus/octree/6/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.08.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method octree6 --sample_rate 0.08 --model_name pointpillars --feature_model none --dataset nus
# python test.py ../configs/pointpillars/resample/nus/octree/6/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.06.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method octree6 --sample_rate 0.06 --model_name pointpillars --feature_model none --dataset nus


# python test.py ../configs/pointpillars/resample/nus/random/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.4.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method random --sample_rate 0.4 --model_name pointpillars --feature_model none --dataset nus
# python test.py ../configs/pointpillars/resample/nus/random/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.2.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method random --sample_rate 0.2 --model_name pointpillars --feature_model none --dataset nus

# python test.py ../configs/pointpillars/resample/nus/statistic/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.4.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method statistic --sample_rate 0.4 --model_name pointpillars --feature_model none --dataset nus
# python test.py ../configs/pointpillars/resample/nus/statistic/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.2.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method statistic --sample_rate 0.2 --model_name pointpillars --feature_model none --dataset nus

# python test.py ../configs/pointpillars/resample/nus/octree/10/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.4.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method octree10 --sample_rate 0.4 --model_name pointpillars --feature_model none --dataset nus
# python test.py ../configs/pointpillars/resample/nus/octree/10/pointpillars_hv_secfpn_sbn-all_8xb4-2x_nus-3d_0.2.py ../checkpoints/pointPillars/hv_pointpillars_secfpn_sbn-all_fp16_2x8_2x_nus-3d.pth --sample_method octree10 --sample_rate 0.2 --model_name pointpillars --feature_model none --dataset nus