python test.py ../configs/parta2/resample/kitti/feat_octree/200/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.5.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_200 --sample_rate 0.5 --model_name parta2 --feature_model pointnet
python test.py ../configs/parta2/resample/kitti/feat_octree/200/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.4.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_200 --sample_rate 0.4 --model_name parta2 --feature_model pointnet
python test.py ../configs/parta2/resample/kitti/feat_octree/200/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.3.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_200 --sample_rate 0.3 --model_name parta2 --feature_model pointnet
# python test.py ../configs/parta2/resample/kitti/feat_octree/200/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.25.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_200 --sample_rate 0.25 --model_name parta2 --feature_model pointnet
python test.py ../configs/parta2/resample/kitti/feat_octree/200/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.2.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_200 --sample_rate 0.2 --model_name parta2 --feature_model pointnet
python test.py ../configs/parta2/resample/kitti/feat_octree/200/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.1.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_200 --sample_rate 0.1 --model_name parta2 --feature_model pointnet
# python test.py ../configs/parta2/resample/kitti/feat_octree/200/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.15.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_200 --sample_rate 0.15 --model_name parta2 --feature_model pointnet

# python test.py ../configs/parta2/resample/kitti/feat_octree/100/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.5.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_100 --sample_rate 0.5 --model_name parta2 --feature_model pointnet
# python test.py ../configs/parta2/resample/kitti/feat_octree/100/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.25.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_100 --sample_rate 0.25 --model_name parta2 --feature_model pointnet
# python test.py ../configs/parta2/resample/kitti/feat_octree/100/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.15.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_100 --sample_rate 0.15 --model_name parta2 --feature_model pointnet

# python test.py ../configs/parta2/resample/kitti/feat_octree/300/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.5.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_300 --sample_rate 0.5 --model_name parta2 --feature_model pointnet
# python test.py ../configs/parta2/resample/kitti/feat_octree/300/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.25.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_300 --sample_rate 0.25 --model_name parta2 --feature_model pointnet
# python test.py ../configs/parta2/resample/kitti/feat_octree/300/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.15.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_300 --sample_rate 0.15 --model_name parta2 --feature_model pointnet

# python test.py ../configs/parta2/resample/kitti/feat_octree/400/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.5.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_400 --sample_rate 0.5 --model_name parta2 --feature_model pointnet
# python test.py ../configs/parta2/resample/kitti/feat_octree/400/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.25.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_400 --sample_rate 0.25 --model_name parta2 --feature_model pointnet
# python test.py ../configs/parta2/resample/kitti/feat_octree/400/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.15.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_400 --sample_rate 0.15 --model_name parta2 --feature_model pointnet


# python test.py ../configs/parta2/resample/kitti/feat_octree/200/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.5.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_200 --sample_rate 0.5 --model_name parta2 --feature_model pointnet2
# python test.py ../configs/parta2/resample/kitti/feat_octree/200/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.4.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_200 --sample_rate 0.4 --model_name parta2 --feature_model pointnet2
# python test.py ../configs/parta2/resample/kitti/feat_octree/200/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.3.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_200 --sample_rate 0.3 --model_name parta2 --feature_model pointnet2
# python test.py ../configs/parta2/resample/kitti/feat_octree/200/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.25.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_200 --sample_rate 0.25 --model_name parta2 --feature_model pointnet2
# python test.py ../configs/parta2/resample/kitti/feat_octree/200/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.2.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_200 --sample_rate 0.2 --model_name parta2 --feature_model pointnet2
# python test.py ../configs/parta2/resample/kitti/feat_octree/200/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.15.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_200 --sample_rate 0.15 --model_name parta2 --feature_model pointnet2

# python test.py ../configs/parta2/resample/kitti/feat_octree/100/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.4.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_100 --sample_rate 0.4 --model_name parta2 --feature_model pointnet
# python test.py ../configs/parta2/resample/kitti/feat_octree/100/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.5.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_100 --sample_rate 0.5 --model_name parta2 --feature_model pointnet
# python test.py ../configs/parta2/resample/kitti/feat_octree/100/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.3.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_100 --sample_rate 0.3 --model_name parta2 --feature_model pointnet
# python test.py ../configs/parta2/resample/kitti/feat_octree/100/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.25.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_100 --sample_rate 0.25 --model_name parta2 --feature_model pointnet
# python test.py ../configs/parta2/resample/kitti/feat_octree/100/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.2.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_100 --sample_rate 0.2 --model_name parta2 --feature_model pointnet
# python test.py ../configs/parta2/resample/kitti/feat_octree/100/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.15.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_100 --sample_rate 0.15 --model_name parta2 --feature_model pointnet

# python test.py ../configs/parta2/resample/kitti/feat_octree/100/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.5.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_100 --sample_rate 0.5 --model_name parta2 --feature_model pointnet2
# python test.py ../configs/parta2/resample/kitti/feat_octree/100/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.4.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_100 --sample_rate 0.4 --model_name parta2 --feature_model pointnet2
# python test.py ../configs/parta2/resample/kitti/feat_octree/100/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.3.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_100 --sample_rate 0.3 --model_name parta2 --feature_model pointnet2
# python test.py ../configs/parta2/resample/kitti/feat_octree/100/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.25.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_100 --sample_rate 0.25 --model_name parta2 --feature_model pointnet2
# python test.py ../configs/parta2/resample/kitti/feat_octree/100/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.2.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_100 --sample_rate 0.2 --model_name parta2 --feature_model pointnet2
# python test.py ../configs/parta2/resample/kitti/feat_octree/100/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.15.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_100 --sample_rate 0.15 --model_name parta2 --feature_model pointnet2

# python test.py ../configs/parta2/resample/kitti/feat_octree/300/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.5.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_300 --sample_rate 0.5 --model_name parta2
# python test.py ../configs/parta2/resample/kitti/feat_octree/300/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.4.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_300 --sample_rate 0.4 --model_name parta2
# python test.py ../configs/parta2/resample/kitti/feat_octree/300/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.3.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_300 --sample_rate 0.3 --model_name parta2
# python test.py ../configs/parta2/resample/kitti/feat_octree/300/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.25.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_300 --sample_rate 0.25 --model_name parta2
# python test.py ../configs/parta2/resample/kitti/feat_octree/300/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.2.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_300 --sample_rate 0.2 --model_name parta2
# python test.py ../configs/parta2/resample/kitti/feat_octree/300/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.15.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_300 --sample_rate 0.15 --model_name parta2

# python test.py ../configs/parta2/resample/kitti/feat_octree/400/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.5.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_400 --sample_rate 0.5 --model_name parta2
# python test.py ../configs/parta2/resample/kitti/feat_octree/400/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.4.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_400 --sample_rate 0.4 --model_name parta2
# python test.py ../configs/parta2/resample/kitti/feat_octree/400/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.3.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_400 --sample_rate 0.3 --model_name parta2
# python test.py ../configs/parta2/resample/kitti/feat_octree/400/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.25.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_400 --sample_rate 0.25 --model_name parta2
# python test.py ../configs/parta2/resample/kitti/feat_octree/400/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.2.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_400 --sample_rate 0.2 --model_name parta2
# python test.py ../configs/parta2/resample/kitti/feat_octree/400/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.15.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_400 --sample_rate 0.15 --model_name parta2

# python test.py ../configs/parta2/resample/kitti/feat_octree/500/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.5.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_500 --sample_rate 0.5 --model_name parta2
# python test.py ../configs/parta2/resample/kitti/feat_octree/500/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.4.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_500 --sample_rate 0.4 --model_name parta2
# python test.py ../configs/parta2/resample/kitti/feat_octree/500/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.3.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_500 --sample_rate 0.3 --model_name parta2
# python test.py ../configs/parta2/resample/kitti/feat_octree/500/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.25.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_500 --sample_rate 0.25 --model_name parta2
# python test.py ../configs/parta2/resample/kitti/feat_octree/500/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.2.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_500 --sample_rate 0.2 --model_name parta2
# python test.py ../configs/parta2/resample/kitti/feat_octree/500/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.15.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method feat_octree_500 --sample_rate 0.15 --model_name parta2

# python test.py ../configs/parta2/resample/kitti/octree/10/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.2.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method octree --sample_rate 0.2 --model_name parta2 --feature_model pointnet2
# python test.py ../configs/parta2/resample/kitti/octree/8/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.2.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method octree --sample_rate 0.2 --model_name parta2 --feature_model pointnet2
# python test.py ../configs/parta2/resample/kitti/octree/6/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.2.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method octree --sample_rate 0.2 --model_name parta2 --feature_model pointnet2

# python test.py ../configs/parta2/resample/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method random --sample_rate 1 --model_name parta2



# python test.py ../configs/parta2/resample/kitti/random/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.5.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method random --sample_rate 0.5 --model_name parta2
# python test.py ../configs/parta2/resample/kitti/random/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.4.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method random --sample_rate 0.4 --model_name parta2
# python test.py ../configs/parta2/resample/kitti/random/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.3.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method random --sample_rate 0.3 --model_name parta2
# python test.py ../configs/parta2/resample/kitti/random/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.2.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method random --sample_rate 0.2 --model_name parta2
# python test.py ../configs/parta2/resample/kitti/random/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.1.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method random --sample_rate 0.1 --model_name parta2
# python test.py ../configs/parta2/resample/kitti/random/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.25.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method random --sample_rate 0.25 --model_name parta2
# python test.py ../configs/parta2/resample/kitti/random/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.15.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method random --sample_rate 0.15 --model_name parta2





# python test.py ../configs/parta2/resample/kitti/fps/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.5.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method fps --sample_rate 0.5 --model_name parta2
# python test.py ../configs/parta2/resample/kitti/fps/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.4.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method fps --sample_rate 0.4 --model_name parta2
# python test.py ../configs/parta2/resample/kitti/fps/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.3.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method fps --sample_rate 0.3 --model_name parta2
# python test.py ../configs/parta2/resample/kitti/fps/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.2.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method fps --sample_rate 0.2 --model_name parta2
# python test.py ../configs/parta2/resample/kitti/fps/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.1.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method fps --sample_rate 0.1 --model_name parta2
# python test.py ../configs/parta2/resample/kitti/fps/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.25.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method fps --sample_rate 0.25 --model_name parta2
# python test.py ../configs/parta2/resample/kitti/fps/parta2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class_0.15.py ../checkpoints/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-3class.pth --sample_method fps --sample_rate 0.15 --model_name parta2